### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by DeIeK** [adrmnt/homebridge-salus-it600-gateway#1]
Installed this plugin, but devices do not appear in homebridge.
Which thermostat models are supported?
I have HTRS-RF(30) / VS10WRF / VS20WRF thermostats and two UGE600 for my homes.
TRV does not supported?

**Comment by adrmnt** [comment]
@DeIeK for now only thermostat SQ610 is supported. 
https://github.com/adrmnt/salus-it600-pack.

**Comment by xyz4tech** [comment]
Was able to get the SQ610RF to work with help of the following issue of the "salus-it600-pack":
https://github.com/adrmnt/salus-it600-pack/issues/1#issue-1088474437
