### ISSUE TITLE
should it works with it600 and uge600?

### ISSUE THREAD

**Issue by wdylag** [adrmnt/homebridge-salus-it600-gateway#3]
nothing happens after configure the plugin. I use the right credentials as I use on saluscontrols.io... please let me know how can I use it.

**Comment by adrmnt** [comment]
@wdylag the plugin was updated. please reinstall the plugin and add your thermostat model from configuration

        {
            "thermostatModels": [
                "thermostatmodel"
            ],
            "username": "emailaddress",
            "password": "passwod!",
            "platform": "Salus-iT600"
        },
