### ISSUE TITLE
Homebridge not recognizing the thermostats

### ISSUE THREAD

**Issue by JurjAlex** [adrmnt/homebridge-salus-it600-gateway#7]
Hello,

I installed this plugin in homebridge but the configured thermostats are not visible.
I also added 2 types of thermostats, VS20BRF and VS20WRF (These are the 2 models I have).

This is how my configuration looks like:
{
            "thermostatModels": [
                "VS20BRF",
                "VS20WRF"
            ],
            "username": "replaced by my actual username",
            "password": "replaced by my actual password",
            "platform": "Salus-iT600"
        }

Is there anything else I need to do?

Thank you!

**Comment by zlugg** [comment]
Log in on https://eu.salusconnect.io and look how your thermostats are identified. 
"iT600 VS Battery Thermostat" = "it600ThermHW" in configuration. 
I think all VS10 and VS20 thermostat are identified as "it600ThermHW".

**Comment by JurjAlex** [comment]
Thank you, it worked
